### ISSUE TITLE
RSA - Encrypt and Decrypt

### ISSUE THREAD

**Issue by tejaChintalapatiPD** [Infineon/python-optiga-trust#10]
**Question/Issue**:

How can I encrypt and decrypt test data using the external and generated RSA Keys?

**Context**

I have the RSA public key sent from the server and I am trying to encrypt the data that's to be sent to the cloud. I want to do what [this function](https://infineon.github.io/arduino-optiga-trust-m/df/d1c/class_i_f_x___o_p_t_i_g_a___trust_m.html#a156f0a83bdab0cfc019b672b234d7873) is doing but in Python. However, I couldn't find references to encrypt and decrypt functions in the Infineon's code.

I know this can be achieved by installing openssl but I would like to understand if I can get the Trust M to do this for me.

Can you please tell me how to do this?

**Comment by ayushev** [comment]
Original intention of this library was to make data object manipulation easier, with no direct focus on the crypto, thus not all functions were added.
I'll add the description of the function in more details later in the [documentation](https://infineon.github.io/python-optiga-trust/), for the time being you can use this [tests](https://github.com/Infineon/python-optiga-trust/blob/master/tests/test_rsapkcs1v15.py#L187-L245)
Do you also need the decrypt?

**Comment by ayushev** [comment]
Fixed in the v1.2.7

**Comment by tejaChintalapatiPD** [comment]
Perfect! Thanks for adding these! Appreciate the help, @ayushev :) 👍
