### ISSUE TITLE
Confusion about missing optiga_trust_charge_m_uart_python.hex

### ISSUE THREAD

**Issue by arne123** [Infineon/python-optiga-trust#13]
Dear all,

I want to use the OPTIGA Trust M Evaluation Kit to program a certificate/keypair on an Optiga V3 via the python-optiga-trust on a windows machine.

I followed the steps to [Enable the provisioning ](https://infineon.github.io/python-optiga-trust/prov_mode.html)

The Issue is, that none of the python examples are working, all calls are basically blocking with a high cpu load
I guess there is a kind of uart communication ongoing, I can not open the corresponding com port with any other tool, when the python scripts are running and the scripts are terminating when I press the reset button on the board. (Error Message below *1)

But I doubt that the hexfile is the correct one for this board in order to get the python-optiga-trust running.

In the sphinx docs, a link to a hex file which should be programed to the board is broken.
(Link is pointing to a file called  optiga_trust_charge_m_uart_python.hex) 

I tried with the optiga_trust_m_evalkit_uart_python.hex form the trust_m branch.

I don't see any I2C Communication with the optiga here (scope connected to SCL/SDA)

Is there any recommendation how to debug this further?

BR
  Arne
  
  
 *1 Error after pressing reset on the eval board:
 
> COM port read failed
Error is 995COM port read failed
Error is 995Error: 0x202
Could not find module '......\lib\site-packages\optigatrust\csrc\lib\liboptigatrust-i2c-win-amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
libusb: Failed to connect
uart: Failed to connect
i2c: Failed to find library liboptigatrust-i2c-win-amd64.dll in .........\lib\site-packages\optigatrust\csrc\lib

I am not sure if the missing dll is just a subsequent fault, trying other communication channels after a failure on the uart or if it is a real issue. The dll is definitely not in the python package, but other like liboptigatrust-uart-win-amd64.dll are.

**Comment by sgsharath123** [comment]
Hello @arne123 ,

We are looking into the broken link in "[Enable the provisioning](https://infineon.github.io/python-optiga-trust/prov_mode.html)".

Are you using the same kit as shown in the link above (...\prov_mode.html)?

**Comment by arne123** [comment]
Yes, I have the 
XMC4800-2048 based board

**Comment by sgsharath123** [comment]
Hello @arne123 ,

We will update the image and upload it for the version 1.3.2.

For now, try the hints below and let us know if you still face issues.
Please downgrade the library version to the 1.2.7 and use [this](https://github.com/Infineon/python-optiga-trust/blob/0f63d1f56d8cd34f8782b1527d170ebfe00f3910/docs/static/optiga_trust_m_evalkit_uart_python.hex) image to flash the kit

**Comment by arne123** [comment]
Dear @sgsharath123 
thanks for your support,
the downgrade to 1.2.7 is working so far, thank you very much.

Please let me know when the updated image is available.

**Comment by sgsharath123** [comment]
Hi @arne123 ,
We will update it soon, please watch this repository for the update.
