### ISSUE TITLE
xmc4800 hex file not available

### ISSUE THREAD

**Issue by maximevince** [Infineon/python-optiga-trust#14]
The documentation at https://infineon.github.io/python-optiga-trust/prov_mode.html
links to a file: Select [xmc4800 hex file](https://infineon.github.io/python-optiga-trust/static/optiga_trust_charge_m_uart_python.hex) (right click, Save), which is not available from your GitHub pages anymore.

**Comment by maximevince** [comment]
There seems to be a version of this binary checked in here:
https://github.com/Infineon/python-optiga-trust/blob/master/docs/sphinx/_files/optiga_trust_m_evalkit_uart_python.hex
See here for all the "python" hex files: https://github.com/Infineon/python-optiga-trust/blob/master/docs/sphinx/_files/

Not sure if it's the same as the documentation is referring to.

**Comment by ayushev** [comment]
Hi @maximevince 

please refer to this link for the time being, we a re preparing an update for the package which shall include the missing link
https://github.com/Infineon/python-optiga-trust/issues/13#issuecomment-1056766936

**Comment by spaehn** [comment]
Dear @maximevince,

unfortunately, the support for XMC4800 (OPTIGA™ Trust M Evaluation Kit) is discontinued.

However, we offer a new variety of Infineon PSoC™ 6 boards for evaluation. See: [https://infineon.github.io/python-optiga-trust/prov_mode.htm](https://infineon.github.io/python-optiga-trust/prov_mode.html)

Best regards, Michael
