### ISSUE TITLE
Optiga Trust M - Repeated Crypto Operations 

### ISSUE THREAD

**Issue by tejaChintalapati** [Infineon/python-optiga-trust#15]
Hi,

I am trying to interface Optiga Trust M with RPi 3B+. To start with, I am trying to generate random numbers with this code:
```
import optigatrust as optiga
from optigatrust import objects, crypto
import json

chip = optiga.Chip()
chip.current_limit = 15

TRNGNumber = crypto.random(8, trng=True)
print("Random Number: {0}".format((TRNGNumber)))

quit()
```

Here's my output **THE FIRST TIME** I run it:
`Python 3.9.2 (/usr/bin/python3)
>>> %Run Optiga-TmV3-RPi-AES-Operation.py
COM39: No such file or directory
Error: 0x202 
Loaded: liboptigatrust-i2c-linux-armv7l.so
Random Number: b'^\xfe\xa5C3\xf7\xe95'`

The from then on, I cannot communicate with the chip. Everytime, it results in the following error:
`Python 3.9.2 (/usr/bin/python3)
>>> %Run Optiga-TmV3-RPi-AES-Operation.py
Error: 0x202 
COM39: No such file or directory

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Python 3.9.2 (/usr/bin/python3)
>>> %Run Optiga-TmV3-RPi-AES-Operation.py
COM39: No such file or directory
Error: 0x202 

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Python 3.9.2 (/usr/bin/python3)
>>> %Run Optiga-TmV3-RPi-AES-Operation.py
COM39: No such file or directory
Error: 0x202`

After waiting for some time(5-10 minutes), the code works fine again without any issues.
`Python 3.9.2 (/usr/bin/python3)
>>> %Run Optiga-TmV3-RPi-AES-Operation.py
COM39: No such file or directory
Error: 0x202 
Loaded: liboptigatrust-i2c-linux-armv7l.so
Random Number: b'lpaV)\xfd\x1dD'`

I noticed this behavior with two different chips and both exhibit similar behavior. Can you please tell me what's causing this issue and what should be done so that I can do crypto operations continuously without a significant delay between operations?

Note: Noticed this behavior only with TRNG generation and not ECDH Operation, which works fine when run repeatedly.

**Comment by ayushev** [comment]
if you run from the command line multiple times the command `optigatrust object --id 0xe0e0` or `optigatrust object --id 0xe0e0 --meta` do you also observe the same behavior?

**Comment by tejaChintalapati** [comment]
I am travelling for work today. I shall check this tomorrow and update.

**Comment by tejaChintalapati** [comment]
Hi,

These commands work just fine on CLI when I ran them multiple times.

Can you try to recreate this in your lab? You may try to run the below code repeatedly.
`import optigatrust as optiga
from optigatrust import objects, crypto
import json

chip = optiga.Chip()
chip.current_limit = 15

TRNGNumber = crypto.random(8, trng=True)
print("Random Number: {0}".format((TRNGNumber)))

quit()`

**Comment by ayushev** [comment]
I can run it without any errors multiple times, but I though such answers don't really help.
May I know as well the hardware connection you have with the OPTIGA and also what is the Linux version you have, for instance by running `uname -a`

**Comment by tejaChintalapati** [comment]
`uname -a` output is:

`Linux raspberrypi 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux`

**Comment by ayushev** [comment]
we usually recommend to connect the RST line of the chip, otherwise you need to rebuild the code for the linux with the reset_type changed
- you need to download the repository 
  ```
  git clone https://github.com/Infineon/python-optiga-trust.git
  ```
- change the the [reset type](https://github.com/Infineon/python-optiga-trust/blob/master/optigatrust/csrc/optiga-trust-m/optiga/include/optiga/optiga_lib_config_m_v3.h#L113) to the **soft reset**
- build again using the [following manual](https://infineon.github.io/python-optiga-trust/linux_support.html)
- (optionally) to keep track of your changes change the version [here](https://github.com/Infineon/python-optiga-trust/blob/master/optigatrust/version.py)
- go to the root folder of the repo: `python-optiga-trust` and run from there `python3 -m pip install .`

**Comment by tejaChintalapati** [comment]
Okay. Thanks for letting me know. I shall try this early next week and give you an update.

**Comment by spaehn** [comment]
Closed due to inactivity.
