### ISSUE TITLE
AES Encrypt/Decrypt Operations

### ISSUE THREAD

**Issue by tejaChintalapati** [Infineon/python-optiga-trust#16]
**Have you looked for an answer?**
python-optiga-trust-master/docs

**Question/Issue**:
AES Encrypt/Decrypt Operations

**Context**
After deriving the key from a shared secret, is there any AES API to encrypt the data?

###### THANKS!
tC

**Comment by ayushev** [comment]
Currently AES encrypt/decrypt operation are not supported, as not needed, but they can be relatively easy added. Is it then a feature request?

**Comment by tejaChintalapati** [comment]
Okay. I would appreciate it if they could be added. This is a feature request.

Can you please elaborate on "**_as not needed_**"?

**Comment by tejaChintalapati** [comment]
Hi, 

Just following up on this. Will this feature request take time?

**Comment by spaehn** [comment]
Dear @tejaChintalapati,

unfortunately, there are currently no plans to support AES encryption and decryption in this Python library.

However, our [OPTIGA™ Trust M Host Library for C](https://github.com/Infineon/optiga-trust-m) supports this feature and you can find two very good examples on how to perform encryption and decryption in our [linux-optiga-trust-m](https://github.com/Infineon/linux-optiga-trust-m/tree/development_v3) project:
* [AES encryption](https://github.com/Infineon/linux-optiga-trust-m/blob/development_v3/ex_cli_applications/trustm_symmetric_enc.c)
* [AES decryption](https://github.com/Infineon/linux-optiga-trust-m/blob/development_v3/ex_cli_applications/trustm_symmetric_dec.c)

Based on the steps shown in the above example, an implementation for Python can be done by extending the [optigatrust/crypto.py](https://github.com/Infineon/python-optiga-trust/blob/develop/optigatrust/crypto.py) source file.

Thank you for your interest in our OPTIGA™ Trust M product and please feel free to approach your local Infineon or distribution partner for more detailed support.
