### ISSUE TITLE
Reason for appending lengths in front of the certificate

### ISSUE THREAD

**Issue by boraozgen** [Infineon/python-optiga-trust#4]
Hello @ayushev,

what is the reason behind adding the length bytes in front of the certificate? 

https://github.com/Infineon/python-optiga-trust/blob/020f77b855a5e63a48b556072c7630c14536114c/lib/optigatrust/x509/cert.py#L176-L184

**Comment by ayushev** [comment]
Hi @boraozgen 
To be compliant with the format which we have to store certificates. This isn't really critical for the certiciate object as optiga doesn't parse it itself, however it is relevant for [Trust Anchors Objects](https://github.com/Infineon/python-optiga-trust/blob/020f77b855a5e63a48b556072c7630c14536114c/lib/optigatrust/util/types.py#L76) 
In general it is compliant ot the certificate representation of different identity types ([SRM](https://github.com/Infineon/optiga-trust-m/blob/master/documents/OPTIGA_Trust_M_V1_Solution_Reference_Manual_v1.13.pdf) Section 5.6 Common Data Structures, Page 130)

**Comment by boraozgen** [comment]
Interesting. Is this a standard representation? My problem was that Mbed TLS could not parse the certificate when pointed to the start of the certificate buffer. I have to add an offset of 9 bytes and point to the `0x30` tag to correctly parse the certificates provisioned by the scripts. Maybe this could be documented somewhere.

**Comment by ayushev** [comment]
For all OPTIGA Trust Products, as internally the device needs to understand which certificate is provisioned (there are many).
You can also call [this function](https://github.com/Infineon/python-optiga-trust/blob/master/lib/optigatrust/x509/cert.py#L40) to retrive the certiicate, optinally you can convert it to PEM format.

**Comment by ayushev** [comment]
> Interesting. Is this a standard representation? My problem was that Mbed TLS could not parse the certificate when pointed to the start of the certificate buffer. I have to add an offset of 9 bytes and point to the `0x30` tag to correctly parse the certificates provisioned by the scripts. Maybe this could be documented somewhere.

We have listed it [here](https://github.com/Infineon/optiga-trust-m/tree/master/certificates) and [here](https://github.com/Infineon/optiga-trust-m/wiki/Keys-and-Certificates) or do you mean additionaly write it in the code along the function?

**Comment by boraozgen** [comment]
I mean when reading from a microcontroller instead of the python script, one must read the slot with an offset of 9 bytes in order to receive a standard DER encoded certificate. Maybe this information could be added to the `optiga_util_read_data()` function documentation in https://github.com/Infineon/optiga-trust-x

**Comment by ayushev** [comment]
Thanks for the feedback. I did update
[First](https://github.com/Infineon/optiga-trust-x/wiki/Trust-X-Util-API#optiga_util_read_metadata), [second](https://github.com/Infineon/optiga-trust-x/blob/master/examples/optiga/example_optiga_util_read_data.c#L53), [third](https://github.com/Infineon/optiga-trust-m/blob/master/examples/optiga/example_optiga_util_read_data.c#L82), [forth](https://github.com/Infineon/optiga-trust-m/wiki/Trust-M-Util-API#optiga_util_read_data) place
