### ISSUE TITLE
Cannot read/write slot 0xE0EF

### ISSUE THREAD

**Issue by boraozgen** [Infineon/python-optiga-trust#8]
**Description**:

During read and write, supported objects do not contain the slot 0xE0EF, which causes an error if this slot is used.

https://github.com/Infineon/python-optiga-trust/blob/ec748b2cb016a231b6dd70f1eabd7940e1fc63fe/optigatrust/objects.py#L217-L219

https://github.com/Infineon/python-optiga-trust/blob/ec748b2cb016a231b6dd70f1eabd7940e1fc63fe/optigatrust/objects.py#L282-L284

`TRUST_ANCHOR_3`, which corresponds to this slot in the enums, needs to be in the list as well.

By the way I tried writing/reading the slot depicted by `TRUST_ANCHOR_2` (address 0xE0E9) and suprisingly succeeded, although this slot is not documented in Optiga Trust X datasheet at all. Is it allowed to use this slot or could it be removed from future hardware?

**Build/Commit:**

master

**Target:**

Optiga Trust X

**Comment by ayushev** [comment]
Hi @boraozgen 
thank you for finding this one! 
you are correct and not at the same time. The `TRUST_ANCHOR_2` for the Trust X is defined as 0xE0EF (0xE0E9 isn't available for this chip), and for other chips as 0xE0F9. So this is why it did work for your case, it should however check as well the `TRUST_ANCHOR_3` for chips which have it

**Comment by boraozgen** [comment]
Hi @ayushev 

I disagree. Here is the related part of the code:

```py
root_cert = x509.load_pem_x509_certificate(root_cert_pem)
root_cert_object = objects.X509(0xE0EF)
root_cert_object.write(root_cert.public_bytes(serialization.Encoding.DER))
```

This results in:

```
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    main()
  File "main.py", line 44, in main
    provision_optiga(args)
  File "main.py", line 97, in provision_optiga
    root_cert_object = objects.X509(0xE0EF)
  File "/home/pi/.local/lib/python3.7/site-packages/optigatrust/objects.py", line 143, in __init__
    self._der = self._read()
  File "/home/pi/.local/lib/python3.7/site-packages/optigatrust/objects.py", line 302, in _read
    'Object ID is not one of supported {0}'.format(_supported_objects)
ValueError: Object ID is not one of supported (57568, 57569, 57570, 57571, 57576, 57577, <ObjectId.DATA_SLOT_1500B_0: 61920>, <ObjectId.DATA_SLOT_1500B_1: 61921>)
```

While this works:

```py
root_cert_object = objects.X509(0xE0E9)
root_cert_object.write(root_cert.public_bytes(serialization.Encoding.DER))
```

How do you explain this?

**Comment by ayushev** [comment]
Sure, I'll try
for this could you please paste the output of this command:

```python
obj = optiga.Object(0xe0c2)
''.join("{:02x} ".format(x) for x in obj.read())
```

**Comment by boraozgen** [comment]
`cd 16 33 84 01 00 1c 00 01 00 00 0a 09 a4 13 00 04 00 45 00 7b 80 10 10 71 08 09`

**Comment by ayushev** [comment]
It look s like you have a Trust M1 Chip in your hand
```
import optigatrust as optiga
chip = optiga.Chip()
chip.name
```
Trust M1 doesn't have the `0xE0EF` object

**Comment by boraozgen** [comment]
That was the last option I was considering. I'll have a strict talk with our hardware engineers :)

Excuse me for the misunderstanding. Anyway, at least part of the issue is correct :)
