### ISSUE TITLE
Cannot connect Trust M - I2C - to RPi3

### ISSUE THREAD

**Issue by tejaChintalapatiPD** [Infineon/python-optiga-trust#9]
**What am I trying to do?**

Connect Trust M to RPi

**Hardware**

[S2GO OPTIGA SECURITY CHIP](https://www.infineon.com/cms/en/product/evaluation-boards/s2go-security-optiga-m/)

Raspberry Pi 3B+

**Configuration**
* Enabled I2C in raspi-config
* Added GPIO to the user group

**Installed Libraries**

```
pip3 install optigatrust
```

**Issue**

I tested the connectivity by running the commands in [linux-optiga-trust](https://github.com/Infineon/linux-optiga-trust-m) git repository and could see the response from the chip. However when I try to get information about the chip from Python, I am getting:

Error: 0x102
I2C: Failed to connect error. 

Can you please help me understand what did I miss?

**Code**
```
import optigatrust from optiga

chip = optiga.Chip()
print(chip.name)
```

**Comment by ayushev** [comment]
Do you see the "Loaded: liboptigatrust-i2c-linux-armv7l.so" message?

**Comment by tejaChintalapatiPD** [comment]
running```python --version``` returns 2.7.16 while```python3 --version``` returns 3.7.3. I selected the interpreter as Python 3 in the IDE.

Here's the output when I try to run the code:
***
Python 3.7.3 (/usr/bin/python3)
>>> %Run Optiga_Trust_M.py
Error: 0x102 
libusb: Failed to connect
uart: Failed to find library liboptigatrust-uart-linux-armv7l.so in /home/pi/.local/lib/python3.7/site-packages/optigatrust/csrc/lib
i2c: Failed to connect
***

**Comment by ayushev** [comment]
How you hardware connection looks like? Is it like this 

![](https://github.com/Infineon/linux-optiga-trust-m/raw/development_v3/pictures/coonection_diagram1.png) ?

Did you change anything in the linux-optiga-trust repo before compilation to let it run?

**Comment by tejaChintalapatiPD** [comment]
Thanks @ayushev.

Earlier I didn't make the connections correctly. I connected the SDA and SCL pins from the front part and not the back as shown here. The I2C isn't working because there are no pull-up resistors on the front side.

On shifting the connections towards the back side, I can now communicate with the chip without any issues :)

Thanks for the help! Appreciate it.
